imagePullSecrets: []

commissioner:
  image: thavlik/bvs-commissioner:latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: 64Mi
      cpu: 250m
  metrics: true
  tokenName: "Vote"
  mongoDB:
    host: ""
    port: 27017
    database: default
    username: {}
    password: {}
    cacert: {}

node:
  image: thavlik/bvs-node:latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: 9Gi
      cpu: 2000m
  metrics: true
  pvc: ""

gateway:
  image: thavlik/bvs-gateway:latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: 64Mi
      cpu: 100m
  metrics: true

dbSync:
  image: thavlik/bvs-db-sync:latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: 1024Mi
      cpu: 1000m
  metrics: true
  pvc: ""

explorer:
  image: thavlik/bvs-explorer:latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: 64Mi
      cpu: 100m
  metrics: true

postgres:
  image: postgres:latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: 1024Mi
      cpu: 1000m
  metrics: true
  pvc: ""

