imagePullSecrets: []

commissioner:
  image: thavlik/bvs-commissioner:latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: 512Mi
      cpu: 1000m
  tokenName: "Vote"

