apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-explorer
  labels:
    app: {{ .Release.Name }}-explorer
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-explorer
  ports:
  - name: http
    port: 80
