apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-commissioner
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  serviceName: {{ .Release.Name }}-commissioner
  selector:
    matchLabels:
      app: {{ .Release.Name }}-commissioner
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-commissioner
    spec:
    {{- if .Values.commissioner.pvc }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.commissioner.pvc }}
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: commissioner
        imagePullPolicy: {{ .Values.commissioner.imagePullPolicy }}
        image: {{ .Values.commissioner.image }}
        command:
        - commissioner
        - server
        - --token-name
        - {{ .Values.commissioner.tokenName }}
        - --node-config
        - "/configs/testnet-config.json"
        - --node-database-path
        - "/mnt/db"
        - --node-socket-path
        - "/node.socket"
        - --node-host-addr
        - "0.0.0.0"
        - --node-port
        - "1337"
        - --node-topology
        - "/configs/testnet-topology.json"
      {{- if .Values.commissioner.metrics }}
        - --metrics-port
        - "9091"
      {{- end }}
      {{- if .Values.commissioner.pvc }}
        volumeMounts:
        - name: data
          mountPath: /mnt
      {{- end }}
        resources:
{{ toYaml .Values.commissioner.resources | indent 12 }}
        ports:
        - containerPort: 80
          name: http
        - containerPort: 1337
          name: cardano
      {{- if .Values.commissioner.metrics }}
        - containerPort: 9091
          name: metrics
      {{- end }}
        env: []
