kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-node
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-node
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-node
  apiGroup: rbac.authorization.k8s.io
